// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminKeyIsSet():Promise<boolean>;

export function GetToken():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login():Promise<void>;

export function SetAdminKey(arg1:string):Promise<void>;
