// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {go_services} from '../models';

export function AdminKeyIsSet():Promise<boolean>;

export function ClearAdminKey():Promise<void>;

export function GetManifest():Promise<Array<go_services.PackFileDto>>;

export function GetServerStatus():Promise<go_services.ServerStatusResponse>;

export function GetToken():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login():Promise<void>;

export function SetAdminKey(arg1:string):Promise<void>;

export function StartServer():Promise<go_services.ServerStatus>;

export function StopServer():Promise<go_services.ServerStatus>;

export function UpdateDns():Promise<boolean>;

export function UploadModpackZip(arg1:Array<number>,arg2:string):Promise<go_services.ModpackUploadResponse>;
