// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminKeyIsSet() {
  return window['go']['main']['Admin']['AdminKeyIsSet']();
}

export function ClearAdminKey() {
  return window['go']['main']['Admin']['ClearAdminKey']();
}

export function DeleteAllFiles() {
  return window['go']['main']['Admin']['DeleteAllFiles']();
}

export function GetManifest() {
  return window['go']['main']['Admin']['GetManifest']();
}

export function GetServerStatus() {
  return window['go']['main']['Admin']['GetServerStatus']();
}

export function GetToken() {
  return window['go']['main']['Admin']['GetToken']();
}

export function IsLoggedIn() {
  return window['go']['main']['Admin']['IsLoggedIn']();
}

export function Login() {
  return window['go']['main']['Admin']['Login']();
}

export function SelectAndUploadModpackZip() {
  return window['go']['main']['Admin']['SelectAndUploadModpackZip']();
}

export function SetAdminKey(arg1) {
  return window['go']['main']['Admin']['SetAdminKey'](arg1);
}

export function StartServer() {
  return window['go']['main']['Admin']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['Admin']['StopServer']();
}

export function UpdateDns() {
  return window['go']['main']['Admin']['UpdateDns']();
}

export function UploadModpackZip(arg1, arg2) {
  return window['go']['main']['Admin']['UploadModpackZip'](arg1, arg2);
}
