// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminKeyIsSet() {
  return window['go']['main']['Admin']['AdminKeyIsSet']();
}

export function ClearAdminKey() {
  return window['go']['main']['Admin']['ClearAdminKey']();
}

export function GetToken() {
  return window['go']['main']['Admin']['GetToken']();
}

export function IsLoggedIn() {
  return window['go']['main']['Admin']['IsLoggedIn']();
}

export function Login() {
  return window['go']['main']['Admin']['Login']();
}

export function SetAdminKey(arg1) {
  return window['go']['main']['Admin']['SetAdminKey'](arg1);
}
