// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLauncherInstalled():Promise<boolean>;

export function DeleteLauncher():Promise<boolean>;

export function InstallLauncher():Promise<boolean>;

export function ResetClient():Promise<boolean>;

export function StartMinecraftClient():Promise<boolean>;

export function SyncMods():Promise<boolean>;
