// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {go_services} from '../models';

export function ApplyClientUpdate():Promise<void>;

export function CheckForClientUpdate():Promise<go_services.UpdateStatus>;

export function CheckLauncherInstalled():Promise<boolean>;

export function DeleteLauncher():Promise<boolean>;

export function GetClientStatus():Promise<go_services.ClientStatus>;

export function GetClientVersion():Promise<string>;

export function GetDocumentation(arg1:string):Promise<go_services.DocumentationDocument>;

export function GetDocumentationList():Promise<Array<go_services.DocumentationSummary>>;

export function GetServerStatus():Promise<go_services.ServerStatusResponse>;

export function InstallLauncher():Promise<boolean>;

export function ResetClient():Promise<boolean>;

export function StartMinecraftClient():Promise<boolean>;

export function SyncMods():Promise<boolean>;
