// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLauncherInstalled() {
  return window['go']['main']['MinecraftService']['CheckLauncherInstalled']();
}

export function DeleteLauncher() {
  return window['go']['main']['MinecraftService']['DeleteLauncher']();
}

export function InstallLauncher() {
  return window['go']['main']['MinecraftService']['InstallLauncher']();
}

export function StartMinecraftClient() {
  return window['go']['main']['MinecraftService']['StartMinecraftClient']();
}
