// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForgeInstalled():Promise<boolean>;

export function InstallForge():Promise<boolean>;

export function StartMinecraftClient():Promise<boolean>;
