// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyClientUpdate() {
  return window['go']['main']['MinecraftService']['ApplyClientUpdate']();
}

export function CheckForClientUpdate() {
  return window['go']['main']['MinecraftService']['CheckForClientUpdate']();
}

export function CheckLauncherInstalled() {
  return window['go']['main']['MinecraftService']['CheckLauncherInstalled']();
}

export function DeleteLauncher() {
  return window['go']['main']['MinecraftService']['DeleteLauncher']();
}

export function GetClientStatus() {
  return window['go']['main']['MinecraftService']['GetClientStatus']();
}

export function GetClientVersion() {
  return window['go']['main']['MinecraftService']['GetClientVersion']();
}

export function GetDocumentation(arg1) {
  return window['go']['main']['MinecraftService']['GetDocumentation'](arg1);
}

export function GetDocumentationList() {
  return window['go']['main']['MinecraftService']['GetDocumentationList']();
}

export function GetServerStatus() {
  return window['go']['main']['MinecraftService']['GetServerStatus']();
}

export function InstallLauncher() {
  return window['go']['main']['MinecraftService']['InstallLauncher']();
}

export function ResetClient() {
  return window['go']['main']['MinecraftService']['ResetClient']();
}

export function StartMinecraftClient() {
  return window['go']['main']['MinecraftService']['StartMinecraftClient']();
}

export function SyncMods() {
  return window['go']['main']['MinecraftService']['SyncMods']();
}
