// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForgeInstalled() {
  return window['go']['main']['MinecraftService']['CheckForgeInstalled']();
}

export function InstallForge() {
  return window['go']['main']['MinecraftService']['InstallForge']();
}

export function StartMinecraftClient() {
  return window['go']['main']['MinecraftService']['StartMinecraftClient']();
}
