// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotificationState() {
  return window['go']['main']['NotificationService']['GetNotificationState']();
}

export function PingPlayer(arg1) {
  return window['go']['main']['NotificationService']['PingPlayer'](arg1);
}

export function SetPingsEnabled(arg1) {
  return window['go']['main']['NotificationService']['SetPingsEnabled'](arg1);
}
