// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notificationagent} from '../models';

export function GetNotificationState():Promise<notificationagent.State>;

export function PingPlayer(arg1:string):Promise<notificationagent.PingResult>;

export function SetPingsEnabled(arg1:boolean):Promise<notificationagent.State>;
